"""Rectification cards. DALEEL drafts; a licensed engineer approves. Nothing here signs anything."""
from __future__ import annotations

from typing import Literal

from sqlalchemy import select
from sqlalchemy.orm import Session

from services.common.evidence import write_evidence
from services.common.models import Approval, AtaChapter, Card, DefectEvent, Signature, Snag

CARD_VERSION = "daleel-card/1"

REFERENCES = [
    "AMM chapter {chapter} task cards for the affected system",
    "CAR-145 A.50 certification of maintenance (DGCA)",
    "CAR-M M.A.403 aircraft defects and deferral",
    "Operator MEL / CDL applicability check",
]


def draft_card(session: Session, signature_id: int, judge_model_version: str) -> Card:
    sig = session.get(Signature, signature_id)
    if sig is None:
        raise ValueError(f"signature {signature_id} not found")
    snags = session.execute(select(Snag).where(Snag.id.in_(sig.member_snag_ids)).order_by(Snag.occurred_at)).scalars().all()
    events = session.execute(select(DefectEvent).where(DefectEvent.snag_id.in_(sig.member_snag_ids))).scalars().all()
    chapter = session.get(AtaChapter, sig.ata_code)
    work_orders = sorted({e.work_order_id for e in events if e.work_order_id})
    tails = sorted({s.tail for s in snags if s.tail})
    body = {
        "title": f"Recurring defect: {sig.canonical}",
        "ata_code": sig.ata_code,
        "ata_title": chapter.title if chapter else None,
        "aircraft_type": sig.aircraft_type,
        "signature": sig.canonical,
        "recurrence_count": sig.count,
        "first_seen": sig.first_seen.isoformat() if sig.first_seen else None,
        "last_seen": sig.last_seen.isoformat() if sig.last_seen else None,
        "tails": tails,
        "source_snags": [
            {"id": s.id, "tail": s.tail, "occurred_at": s.occurred_at.isoformat() if s.occurred_at else None, "text": s.raw_text, "source": s.source, "source_doc_id": s.source_doc_id}
            for s in snags
        ],
        "work_order_ids": work_orders,
        "proposed_action": (
            f"Treat as a repeat defect under CAR-M M.A.403. Raise a root-cause investigation for {sig.canonical.lower()} "
            f"on {sig.aircraft_type or 'the affected type'} (ATA {sig.ata_code}). Review the {len(work_orders)} prior rectifications "
            f"for common replaced parts, and withhold further MEL deferral until the certifying engineer confirms the root cause."
        ),
        "references": [r.format(chapter=sig.ata_code[:2]) for r in REFERENCES],
        "drafted_by": judge_model_version,
        "card_version": CARD_VERSION,
        "disclaimer": "Draft generated by SIYANA DALEEL. Not a maintenance instruction until approved and signed by a licensed engineer.",
    }
    evidence_id = write_evidence(
        session,
        module="daleel",
        model_version=f"{CARD_VERSION}; judge={judge_model_version}",
        payload="|".join(str(i) for i in sig.member_snag_ids),
        confidence=min(1.0, 0.5 + 0.1 * sig.count),
        source_ids=[*sig.member_snag_ids, *work_orders],
    )
    card = Card(signature_id=sig.id, status="DRAFT", body=body, evidence_id=evidence_id)
    session.add(card)
    session.flush()
    return card


def approve_card(
    session: Session,
    card_id: int,
    *,
    engineer_name: str,
    licence_number: str,
    decision: Literal["APPROVED", "REJECTED"],
    note: str | None = None,
) -> Card:
    if not licence_number or not licence_number.strip():
        raise ValueError("licence_number is required: only a licensed engineer can approve or reject a card")
    if not engineer_name or not engineer_name.strip():
        raise ValueError("engineer_name is required")
    if decision not in ("APPROVED", "REJECTED"):
        raise ValueError("decision must be APPROVED or REJECTED")
    card = session.get(Card, card_id)
    if card is None:
        raise ValueError(f"card {card_id} not found")
    if card.status != "DRAFT":
        raise ValueError(f"card {card_id} is already {card.status}")
    session.add(Approval(card_id=card.id, engineer_name=engineer_name.strip(), licence_number=licence_number.strip(), decision=decision, note=note))
    card.status = decision
    session.flush()
    return card
